version: 

models:
  - name: dim_d7_accounts_currnet
    description: log current account info in effect
    columns:
      - name: accout_id
        description: account_id
        data_tests:
          - not_null
          - unique 
  
      - name: account_name
        data_tests:
          - not_null
      
      - name: contract_tier
        data_tests:
          - not_null

      - name: billing_region
        data_tests:
          - not_null

      - name: current_since
        data_tests:
          - not_null

  - name: fct_d7_orders_attributed
    description: fact table recording order with historical contract tier and regions
    columns:
      - name: order_id 
        data_tests:
          - not_null
          - unique
      
      - name: account_id
        data_tests:
          - not_null
      
      - name: order_ts
        data_tests:
          - not_null

      - name: order_amount_usd
        data_tests:
          - not_null
      
      - name: tier_at_order
        data_tests:
          - not_null
          - accepted_values:
              arguments: 
                values: ['STANDARD', 'PREMIUM', 'ENTERPRISE', 'UNKNOWN']
      
      - name: region_at_order
        data_tests:
          - not_null
    
      - name: current_tier 
        data_tests:
          - not_null