version: 2
models:
  - name: int_d8_employee_history
    columns:
      - name: employee_id
        data_tests:
          - not_null 

      - name: dbt_valid_from
        data_tests:
          - not_null 

      - name: is_deleted
        data_tests:
          - not_null

      - name: is_current
        data_tests:
          - not_null